# Generated by Django 4.2 on 2024-08-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_is_active', 'Может блокировать пользователя')]},
        ),
    ]
