# Generated by Django 4.2 on 2024-08-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='last_sending',
            field=models.DateTimeField(verbose_name='последняя отправка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена'), ('cancelled', 'отменена')], max_length=9, verbose_name='статус'),
        ),
    ]
