# Generated by Django 4.2 on 2024-08-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
